/**
 *
 *  auth.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "auth.h"
#include <string>


void auth::getOne(const HttpRequestPtr &req,
                  std::function<void(const HttpResponsePtr &)> &&callback,
                  std::string &&id)
{
}

void auth::get(const HttpRequestPtr &req,
               std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void auth::create(const HttpRequestPtr &req,
                  std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void auth::updateOne(const HttpRequestPtr &req,
                     std::function<void(const HttpResponsePtr &)> &&callback,
                     std::string &&id)
{
}

/*
void auth::update(const HttpRequestPtr &req,
                  std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void auth::deleteOne(const HttpRequestPtr &req,
                     std::function<void(const HttpResponsePtr &)> &&callback,
                     std::string &&id)
{
}
